chore : 로직 수정

diff --git a/.github/workflows/PlistCICD.yml b/.github/workflows/PlistCICD.yml
--- a/.github/workflows/PlistCICD.yml
+++ b/.github/workflows/PlistCICD.yml
@@ -60,20 +60,18 @@ jobs:
             echo "Setting CURRENT_UPSTREAM=$CURRENT_UPSTREAM to GITHUB_ENV"
             echo CURRENT_UPSTREAM=$CURRENT_UPSTREAM >> $GITHUB_ENV
             
-            if [ $CURRENT_UPSTREAM = blue ]; then
-                echo "Switching to green. CURRENT_PORT=8081, STOPPED_PORT=8080, TARGET_UPSTREAM=green"
-                echo "CURRENT_PORT=8081" >> $GITHUB_ENV
-                echo "STOPPED_PORT=8080" >> $GITHUB_ENV
-                echo "TARGET_UPSTREAM=green" >> $GITHUB_ENV
-            elif [ $CURRENT_UPSTREAM = green ]; then
-                echo "Switching to blue. CURRENT_PORT=8080, STOPPED_PORT=8081, TARGET_UPSTREAM=blue"
+             if [ $CURRENT_UPSTREAM = blue ]; then
                 echo "CURRENT_PORT=8080" >> $GITHUB_ENV
                 echo "STOPPED_PORT=8081" >> $GITHUB_ENV
+                echo "TARGET_UPSTREAM=green" >> $GITHUB_ENV
+            elif [ $CURRENT_UPSTREAM = green ]; then
+                echo "CURRENT_PORT=8081" >> $GITHUB_ENV
+                echo "STOPPED_PORT=8080" >> $GITHUB_ENV
                 echo "TARGET_UPSTREAM=blue" >> $GITHUB_ENV
             else
-                echo "Error: Unexpected CURRENT_UPSTREAM value: $CURRENT_UPSTREAM"
-            exit 1
-            fi
+                echo "error"
+                exit 1
+          fi
 
       - name: Docker compose
         uses: appleboy/ssh-action@master
@@ -89,7 +87,7 @@ jobs:
       - name: Check deploy server URL
         uses: jtalk/url-health-check-action@v3
         with:
-          url: http://${{ secrets.LIVE_SERVER_IP }}:${{env.STOPPED_PORT}}/sc
+          url: http://${{ secrets.LIVE_SERVER_IP }}:${{env.STOPPED_PORT}}/env
           max-attempts: 3
           retry-delay: 10s
 
